---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgA2hnxydH0m0f3lOQ6CNqAFIsPnM+IVSX0NfQEeb32HatOR1ZWvhSjnMTl0BKm0HbtVcAscEYgYICfETv9BJ/jJWtUa+eXMeQPtRZ7uapa2wd4Ai1MDaRAIT8Y4Jog0d3vGRzmoJGg2XRRUVzKNWRuKEcX6OlTyY0i/9det/Gi5W4rqZd50DwrgezOkFCx2H74rCWiOKFDe19IVxeQW/IoRb2v3NTKPAOr8cVORt/y0Yheuh6pWQtbPV9C9WMWH/ZDuq3PKHM8xchMtaITWuTY6OJ9XJC5LSAhdwE7EL8HHmYh72BDDfUM7duwQ/n0ZkO+43ruX86ijiojMa2x3fuSgTqCzHQYz/niU1uKueuc+/RypgwFXHhju+tcyf1470TbQyg+NRJqfDbSMaUdUyOeqFrQsDquueyGlRgplYbCdrJqdttiA/BZJfnA/cCp7F9dyDQHCqUAohuRX5L60xE+Uxv0J2pg7zP27R9xovrVhlLdvvch+58ClUlZeO6VT7VLj72bHTCtjwohk4bSvbqjdw4AXDN8SCCDhdzE58A2GvMaw3rG+ZvuoRU9uiBMg1ztKDZ00Dd6Tn9fNslHFoouEBiZZ3Uej35ecbUUOm8xXBL+P2zj7N1zGnktp/vOTsFXInMnXYMt2p6hP5AdsNBOAm8C2twpIqRdUmNYYBArc7TNHvfhawCYFzXV8yVhD1BXmMCC8WBbcedwTtRQIx6fmcmk+xzRKSqj+PajYPgMsM/fySO8VebcHbScJD2lKAT7T1Uv8FmePRjC0c8rGmpWhH8q3SoMP3rObHTb3m+ERAs35ao7YMq4NktoJagKrXdEDcJ0Ow6/OpEKYBN2pVvrhD86Iln0u
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
