---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-secrets
  namespace: media
spec:
  encryptedData:
    PROTON_WIREGUARD_PRIVATE_KEY: AgAvkVx5AplToETQFZN0hnT5kMwOWM/WU8RDL+tDOluBAfPJkH1azUW20Vo4FXUV+nItjNL5BiVSBmqD6y0A3xbeHTMvA0m3ewakZ0bS2j9gxKv8D++Dio3uobbNrZt752r8Y9vjf3jNZ6BH8z1Xe/zWlLZ/jwArGD954W3/EPEgX2mPalB4SikNGyfhjAbjKe9kE15DN7EnXHQc9c2PqMIWGdClJx/ptkFCeNm5b0SYVU18gGcqkAa8jQddd1Hoac316mnriIepX0CJxc4+S1p6v6iylMy+YNvZkcYRfdlyaBd5tY236nhS4sgqEfKsdUnh5YDCI6RWOoSZM2eOogSBOiXheCMsPmTUBuG5nyZerA2doNh7IP5orBRxaK0WpUbGhD9ZrbqV+3NWSO5IqaOzZtEKm7/vEnEidKFlNqqMBCI8uuLdFll4Trs1/iil6kYiPYrO6avN5Y/6qf3Qyow+PoL6050jkCtIUZVo1S+t+hRqz5Y8/OyI2OUVAxjuzwu56wmPPHFx3WaV5ey9ruYXRJZqMmnvD8yvhGSfV3ZrkbAkvGH7BYkoFkweYKIQ+MA8HzVxXQ+3p/oBqPdsrzYpeBAEMAOTdc8EQmRPaE1k1eT0ZEhhNm3vVnbzPZ/PtFILA+2MIvZ9Gi9RauQBSxzGeHvFY/khMjXOu1MmlZ80Lm+u0peQUUH1r6um8/hZ4tUukflPq0ErvHwLSjFqUZalkJrXlG2P+zfqZH2AY63KJYZubxzjcmUEHhPHXg==
  template:
    metadata:
      name: media-secrets
      namespace: media
