{{- if and (not .Values.existingSecret) (not .Values.generateEncryptionKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trek.fullname" . }}-secret
  labels:
    app: {{ include "trek.name" . }}
type: Opaque
data:
  {{ .Values.existingSecretKey | default "ENCRYPTION_KEY" }}: {{ .Values.secretEnv.ENCRYPTION_KEY | b64enc | quote }}
  {{- if .Values.secretEnv.ADMIN_EMAIL }}
  ADMIN_EMAIL: {{ .Values.secretEnv.ADMIN_EMAIL | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ .Values.secretEnv.ADMIN_PASSWORD | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnv.OIDC_CLIENT_SECRET }}
  OIDC_CLIENT_SECRET: {{ .Values.secretEnv.OIDC_CLIENT_SECRET | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and (not .Values.existingSecret) (.Values.generateEncryptionKey) }}
{{- $secretName := printf "%s-secret" (include "trek.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $key := .Values.existingSecretKey | default "ENCRYPTION_KEY" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ include "trek.name" . }}
type: Opaque
stringData:
  {{- if and $existingSecret $existingSecret.data (hasKey $existingSecret.data $key) }}
  {{ $key }}: {{ index $existingSecret.data $key | b64dec | quote }}
  {{- else }}
  {{ $key }}: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_EMAIL }}
  ADMIN_EMAIL: {{ .Values.secretEnv.ADMIN_EMAIL | quote }}
  {{- end }}
  {{- if .Values.secretEnv.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ .Values.secretEnv.ADMIN_PASSWORD | quote }}
  {{- end }}
  {{- if .Values.secretEnv.OIDC_CLIENT_SECRET }}
  OIDC_CLIENT_SECRET: {{ .Values.secretEnv.OIDC_CLIENT_SECRET | quote }}
  {{- end }}
{{- end }}