apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.goauthentik.io'
    chart: authentik
    targetRevision: 2026.2.2
    helm:
      values: |
        global:
          image:
            tag: "2026.2.2"
            
        authentik:
          envFrom:
            - secretRef:
                name: authentik-app-secret
          envValueFrom:
            AUTHENTIK_POSTGRESQL__PASSWORD:
              secretKeyRef:
                name: authentik-db-secret
                key: password
                
          default_http_protocol: https
          error_reporting:
            enabled: true
            
          postgresql:
            host: "authentik-db-16-cluster-rw"
            name: "authentik"
            user: "authentik"
            
        server:
          deploymentStrategy:
            type: Recreate
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
            hosts:
              - "auth.thivillon.org" # Pense à adapter si ton domaine a changé
            paths:
              - /
            pathType: Prefix
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: authentik-data
              mountPath: /data
          volumes:
            - name: authentik-data
              persistentVolumeClaim:
                claimName: authentik-data-pvc
                
        worker:
          deploymentStrategy:
            type: Recreate
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - name: authentik-data
              mountPath: /data
          volumes:
            - name: authentik-data
              persistentVolumeClaim:
                claimName: authentik-data-pvc
                
        postgresql:
          enabled: false
        redis:
          enabled: false
        monitoring:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
