---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-secret
  namespace: auth
spec:
  encryptedData:
    password: AgAC2B+NFf4+rZ7kWFbgh36c4g9MzIp72+XCl+oIpV+spxUUOae1m1PVUvmJAEWpWNztaoVQYeU//+srGp9O2cI8zfYfTTZztYFPzejBNgNl1tqx/lx1g0JTmzNXoEBGcNgQXAxdYE+vXQUoBSsgCleCXj1sfDx9k2PxRj/ioT2vGQzqDU7REql344Y4p5qjmYBRwTr/LOt5SY1dGkFjSgvbRIvOl1/R3pb5+SM2Eb9+XvRETtL6/1u8zV6jRr5PcqjRaZYs856y8RRhvmQJ6Xecx952jAycnzerVEQdiMKM1yHchAiIMnLoKSfa2F6MhK5Mjo/TKLBp59JapLUpR1jvKsg6OHYgSolvftqxslwDE7mwMoRDQ9CDhb6hvRyAtV7sLZyq3B3/m8xCTrcb5GBi9AZMr0YdHgbdDFHbsUpia/YVSi3h9GKZ+pYQXiAZftQjchaz/6U+gD1kj06iG+qrt6lrs9rlD1oZ1eFZ7Xk6gONMMSQVOQBkXkTWlZwkH5hqD2rvc/Qf4JYhikiORw1yzwQKz0ZUD4iv8kDpyW67FR6i3Nb4ThB6W25TIRn5M2nOFfyjBZZFUm0OdA/tiBrpAfXh6o63mgvylsN2iINochKapKsHoGS5LKDyaeX5wThJByETeWGAzH4bocPsjnoFpFtQQupa3usYEOzS4TnZqJBOnE75mnguRlvw/fcr5J7BuRWGEVLWUwioYotWKnsKb5nx7+WrC7doO8Zg8a65VNuOLRkIDj807f8dIAaOmirOy0vpsd9n0yU63ZZ5oSfr
    username: AgDWc+U5cTjLaCnkgNqvKWX8G310Ojl2H/heMvASSr4Jm+BDxFUs1JBqKdSOM8I0Sc6NYT/OxThrr4QN87fc35os6mgnigazV64bw3XyVXeJt5Ab4eeC/h5AWzvOKQHT3q1UY/emBc49ib0g1+VQUtmMxqptJJtVTT/uv1r2SiTmbfGSWLw4sknGBmA32eYffRVmUPWSEFx6bvxlZYQV06Q+0cZAT62bPNcWgk6ygQe4YZSEOg90wHTwnrg4uQvrtSnZdCFZAWA7f9d/kj/W0XW12vKaF8NufctQucv872Cea44L12SsFOX1+MguHLcLStvDx5F5d5HqDHjMcrDp6r826W410NlFOXI55CzAkciQVYp/QCZgvIQvHu3wnLq2frgi1AlsCdFqovcg35SeD0UwX9fO19IAD9Zjd/zLKnbS9NTnm0LEXwsEqpfW4SKZZTv9FD9jwUQD4lVLM/mGILhW3rcaM/mKWXMGRCcK5siM+qkkz85qFdqhU4iGHvdMM3uglFhHdTpBAoDFusXqmxTFZqtsqR7aPZDvYDZgHLyI7CTqdyi8oPdWaOvjElATDW/9C1r7678lgzgZoU1MrJJlbV0ejnVCG3aN7pfNNYT3WgQcPt11mElRUqosrcWeDIId2bqKVHnes+qx7NJSrdM18OKKk3xGJwNm91gmpeJCetej0RN/Yb8AZieNGwsdgsjxkIFGgOhatMc=
  template:
    metadata:
      name: authentik-db-secret
      namespace: auth
    type: kubernetes.io/basic-auth
