apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db-16-cluster
  namespace: auth
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-config
  enablePDB: false
  affinity:
    topologyKey: ""
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    enabled: true
    isWALArchiver: true
    parameters:
      barmanObjectName: authentik-s3-store

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret
      # --- TEMPLATE DE MIGRATION (Pour le futur cluster authentik-db-17) ---
      # import:
      #   type: microservice
      #   databases:
      #     - authentik
      #   source:
      #     externalCluster: authentik-db-16

  # externalClusters:
  #   - name: authentik-db-16
  #     connectionParameters:
  #       host: authentik-db-16-rw.auth.svc.cluster.local
  #       user: postgres
  #       dbname: postgres
  #     password:
  #       name: authentik-db-secret
  #       key: password
