---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-s3-credentials
  namespace: auth
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAu4yKHq3P5MmxZA3P0FsAMKNjMOYYfxMia13XKytBbWFMfHPeMTaVuhzn52s7o08LGW+3VVfbygA+wteJ/Stg6kFdfJmT7BOr8iZUZ7yt0SzABzvrfSu+ynQKcjHaSD6AXmBWZqSfWhF2HEzSXipAlSjj1r2UTyK1GvOxirQYjgSeI6Fx4Czqu85C/kO7XCYp0lHxDEmV5DyHZWVRgTxfyPh0eM5iLgEfcfOsiNt4DFOu++6l8bzeLQdF+Q9X9F28kIaFBydIszyEn+/UnYbjiyS5CUwXsknOEGD4SeVzw2DEKuAZE/ea35+tc+IZAlBZ3Z1yd1gm5DEw3atoF14B5poL3IS5lJOw8L2CvuV5qzb/WdPAjSrHpyFkp3RIcKd4SRYIzkNiv6//AuM4B3SBbR8SVekw0kY5MrN+/Ib4i9IuSHUQd6Z+VzKo8gK1lQUdOSNTXjY49ipOn4GeQf9sfeo+YsFtZ8lLywz1aD8OFUtEtONYXuWELqxYJwX2zqbpuIogTyemhTFeYlf3CSx8jNbWfGwk+/5VOrPvRGEd5Asl0GadmvmMOBZJqQZB3yZlNYtafzIixPoilXFtDjT44C6zDkBzaud0rge3cNLE9TdoblRxW6sbYaymQmpvEuln5M982MOn7nCpsz93IB0hlNRXCYhfFbPtzlN9C9m0rjIy6D3hSrK3VVu4ktJP0qy5WAHOnydicjkHrC+gLJADhf1ETnqEsJHrK1g==
    ACCESS_SECRET_KEY: AgBILaH+2AvEzru0tXO4fFbFVFTWylE/JH7BRX4Em/Z3xCOdgJ2w3ItcBM9PYKEk4t4Vl6EkGh8palFgWtwP49RyPQlh0L5rR2w40S4iuiWliL3asSAM705c7CQrBCs+CqUcZR5SRLiKTMez/1NtvPjzovWay3gPNauopwTfYkdYCtXpezih83c/uez9dd/PPhCWfmsngEQ1HRsK8sOU1Ok+ed7r+rGTWU6KZQsShrkMVlfhctf2hJLueu1oxJwhR/PKAzBRK1RUrb4cd2L3/8REKCoAvvL4KpSjETz/QleL+KDirpBvHqGs1QhaRSpLvZ1FE4XtoLSQD5iF3EAyLHFRilUjk8jsZ7SXlUHVVx6ulSECTycmwzW+HEbEA0YMTbWTUB8iJ6+gO3ihHcrrk0aWDIe5klf1Xi+u2K1KeWsj5WiFa0O1w5ujqF7pkrTwhRes4EYgQRUApHmoKXYK2uCmevBJWF3swIReN5W/691/y9rZHWAeWzPDi/5wuAAUAuvL29lP+p9WtmKBjenVIKoRCTBdxJeeEp58uvwo6ZxEnVBdz2Tp3oSMs8hcdON0WulgWAlKzM6bX2uIA0SGo4DGCFRMOeTTy59nwsdJCMPdXtExRsQD8GPDHW9SErMrWeVkNeN9Qkf9PJLKrdYNhq4Md7eZA6heNWUnOQG9NId+bMBXlhJQY7koTODxLDRysPPbblEp9me/aZW64MZy/n98y8T/WGJPAsvANnJ6tUZMoTNK6qehtzjnNwc0qUx+QkqrSirsCa9yqC3cD97Hh2lR
  template:
    metadata:
      name: cnpg-s3-credentials
      namespace: auth
