apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-s3-store
  namespace: auth
spec:
  configuration:
    destinationPath: s3://cnpg-backups/authentik
    endpointURL: http://100.114.35.5:3900
    s3Credentials:
      accessKeyId:
        name: cnpg-s3-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
