releases:
  - name: cloudnative-pg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    version: "0.27.1"
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
