---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trek-secrets
  namespace: trek
spec:
  encryptedData:
    ENCRYPTION_KEY: AgACHJ6sbMTCBcXIQFTnVYvBWbmkRBJRNTYV2LF39oiJ5NE1Yi0uW7b5HGhNrRgy3nddYrKFqlbivt1Gsz+R1GE+rrnIh1QqN6FH52Lh7+u6oY8+yE5nuxH8gNQ/n6y8W9N3tAcHlWC0j11xTmRUvFvE6DV1+uGn2GEKV+4Eh7JdZYTFOmMdO9+0ubhuITzvetrkVfHeSI7rPGdSbazyJb03/OnCcJECOPgIXfnLgfxgTsZUBxR2xADjD4DupH4N3hKUmKqSLskC4oCbwDnprSiVxuzKVJnRMi+wK3Zr8TwXRqHzEKLZCN3uyy62E6CaTSdvQCYo1DLPjLXkeWR7j31xwuRqkN77UvHafd18M8AyzMhL/m73ZrGtqPHMuwy670+5df6fPRudKW11n0pCEMMIYQoNOyk2shBun1sU1AN4xukh/HkFfzruxJ6jYHQg9WtFH0uMxkelx+97i30M0WLH8FedVXafNPTRfXVCJxU/BbWzJFKGtSOZaTJXYPOu1j6PGWXMM8wXry7s24Lhl+23qymX5mmP8hMr20H20SPSutS4IOBgoLakuD2Pbvnj8REXzJgNqWLE0jebiJGP8yu7YGImEB2/8xb3BWIYKYvztyAUQBP6aFF+5jg17kaHIPQHxOgtmf0TTkSDYVAIRU/BQ78muY/WEDbgu0c/uFVhdaY9dqvPaNvPqK78BVB/2DOlhJEtT4URIl//WNQCBO7vYLpv3919udZsolaQE44y7zIT02J2N3e2fM6SNDWxEOz882X+DMzlO92012vMuyIV
  template:
    metadata:
      name: trek-secrets
      namespace: trek
    type: Opaque
