controllers:
  jellyseerr:
    containers:
      app:
        image:
          repository: fallenbagel/jellyseerr
          tag: "latest"
        env:
          LOG_LEVEL: info
          TZ: Europe/Paris
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: jellyseerr
    ports:
      http:
        port: 5055

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-config
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /app/config

ingress:
  app:
    enabled: false
