apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    chart: velero
    targetRevision: 12.0.1
    helm:
      values: |
        snapshotsEnabled: false
        upgradeCRDs: true
        credentials:
          useSecret: true
          existingSecret: velero-s3-credentials
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: "velero-backups"
              config:
                region: garage
                s3ForcePathStyle: true
                s3Url: "http://100.114.35.5:3900"
          uploaderType: kopia
          defaultVolumesToFsBackup: true
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.11.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        deployNodeAgent: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
