---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBLbPSd41LFX1IfLocCGTEHIDgF0gSaWGYVJYm8CnbcEaXBW+SMbNMsqYrx/Rf72U5JLis5AlFZ/ZpTI5JDmzOmEUZU7iGTRctrtuNdGn4YZxs8w12PH14vFZtv2l2V/kgpDTe/y32MUc3l5rNcd8iwky9Vkr3IFr+pyv8efMPH9+LJ+h+vFmmq3ilhyrLq0fcson7gVBaEBAw9YV44FozpbAgSjL8HRpcZO3RCoHpyYz6iGyV3WoitZZIndvEmIoPFQLPEOrXRNl19KyGycO7xj+FeGHE7EZF7pSjpb0D8bkh1KJlZXAxHMAk5CvnJdqpE7f7HZXZq8NzCGEmjPhDgpWpO58RqZ5yCa3+wAYdZy1lw5Eeg/vYOujt7UJca8WJieqSVWQupcICshhSqiopV8Te8VzH6tsQbfOcNtycs4R0WoUSPIvR+hHfwB/j0IAxStPWvxlnvymTJh7iDyy/2CBFUcCnWPAffQ3vpIk9lNbXzIyr8CaVVMCbEPuUcY3SUMIJQJUK4LwsXTyxVzzbldScA8rfSE1dzIr7O1sr/W3r3tcblbboFGCI0T8h6nTCeUbmeCw1UnbLpEpSHtdwlNIFeKK8eQ+2/6+rcajf33TtdUiJ+4gGTC8NuKIeKT5Z9g5ppyFi7rrSG4PkCXplfDlOINnDASSvkdbWwZhT+QK/sYAm2sdWX/g//sIOFd5LajET8uDZh2RlgaEwfQE5s95H5Gj5jh2GQWoyV1Afhu001Od8zpa6cAsZk1+R3JaCnM1WKQyQ136GT1l5wfos6HMCjuhidaaAvFxxrlKjVwY9X4sI3/cV894tDnfj1/IYgGv/0fPHFwIb9A0fUrWDTtkLOKrAjPa7mu/3/tw2AbV8FLDHvrvi8deEL6Oip
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
