---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgDSUZ1bR0EZjYuwBkSFa/pzgPsH0LOWb38BCe+7EGzsqVtuRqWDHX/UDX/LrlMuIFyj6+ml+ac9TNn171BW7hydwdZjmYEjRF+RaALOhrN3oJgkxibAXA/IfeZ9GoDtCEyobbyRLnVv3hsZyfGFpiUTxO4xKvMPoAdaBq439tRS2WKXiNBwdBF2VjUl/nVrlTCAY0K0ahAaYfvkoyukYJgd2sj3ZAurNHh3awgchygYy5yui6NR2uQMECqV33FYEtZ/J5OZEV0JVl8DNMRqRntk8zCxMg21sO1PiroE/bD6xOXHdX7+cCKxIo8AQFsveSBgfvWMtwTCsoMfnhcOZZs+2kQZVFL0YjvsQawfT5FR2m5nGN1XEgfLqAe/8iwCQu2z05m5uyBo+Rsbx4SSOs/+Dv8O+Or6k3JvUy/Cs0jqG4ApajFUfY4oK6urezsLg8lVwi0lpXBWyez42HEaCJG8rXPJDMOT++PEaXpkr1Ke2i0PNfn3O2F7CM3wuD6eg5fuoi/YktNnoppeNI4B536cqg8n4qvMe83gsDlNFPWTW/SZbIqF7CUZVEG1cRHB0b8GGHES+S1pYq8yrhfmv6e+rh3Fxdy9ifNOccUjffke1D20VNBIaBvl10MeDMivzqAm3JM0i0EzQXW6zZSEOkDJtz2LSCiDw36sIwNs4wMfTliXDhD4GJmlfoINzI1FHum1k62v/qizCw7SdDLKAZ+gbYhCTQ1GW3G+fXM2dGiFPxkqpcANpInoiXeh0taWrIAtRXe3jw==
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: traefik
