apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: 39.0.8
    helm:
      values: |
        # Désactive le Service LoadBalancer par défaut de k3s — on utilise hostPort
        service:
          enabled: false

        # Configuration des ports
        ports:
          web:
            # Le port interne du conteneur DOIT être > 1024 car Traefik n'est pas root
            port: 8000
            # Mais k3s va mapper le port 80 du node sur le port 8000 du pod
            hostPort: 80
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
            forwardedHeaders:
              trustedProxies:
              - 192.168.1.124
              - 2a01:e0a:469:f0a1::5b0
              - 2a01:e0a:469:f0a1:b70a:e809:38ec:6254
          websecure:
            # Même chose pour HTTPS
            port: 8443
            hostPort: 443
            forwardedHeaders:
              trustedProxies:
              - 192.168.1.124
              - 2a01:e0a:469:f0a1::5b0
              - 2a01:e0a:469:f0a1:b70a:e809:38ec:6254

        # Persistence pour stocker acme.json entre les redémarrages
        persistence:
          enabled: true
          storageClass: local-config
          size: 128Mi

        # Configuration du déploiement
        deployment:
          initContainers:
          - name: volume-permissions
            image: busybox:1.37.0
            command:
            - "sh"
            - "-c"
            - "touch /data/acme.json && chmod -v 600 /data/acme.json && chown 65532:65532 /data/acme.json"
            volumeMounts:
            - name: data
              mountPath: /data

        # Stratégie de mise à jour pour éviter le conflit sur hostPort (port 80/443)
        updateStrategy:
          type: Recreate

        podSecurityContext:
          fsGroup: 65532
          fsGroupChangePolicy: "OnRootMismatch"

        # On ajoute le token API en variable d'environnement pour le conteneur Traefik
        envFrom:
        - secretRef:
            name: cloudflare-token-secret
        # On met à jour le résolveur
        certificatesResolvers:
          letsencrypt:
            acme:
              email: "nope@thivillon.org"
              storage: /data/acme.json
              dnsChallenge:
                provider: cloudflare
                # Cloudflare a parfois besoin d'un peu de temps pour propager le TXT
                delayBeforeCheck: 10
                resolvers:
                - "1.1.1.1"
                - "1.0.0.1"
                - "2606:4700:4700::1111"
                - "2606:4700:4700::1001"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi

        # Traefik Providers
        providers:
          kubernetesCRD:
            enabled: true
            allowExternalNameServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true

        # Arguments Traefik pour le File Provider
        additionalArguments:
        - "--providers.file.filename=/etc/traefik/external/services.yaml"
        - "--providers.file.watch=true"
        - "--providers.kubernetesingress.ingressendpoint.ip=100.68.81.91"
        # Montage du ConfigMap externe via le helper "volumes" du chart
        volumes:
        - name: traefik-external-services
          mountPath: "/etc/traefik/external/"
          type: configMap

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
