controllers:
  affine:
    containers:
      app:
        image:
          repository: ghcr.io/toeverything/affine-graphql
          tag: "stable"
        env:
          DATABASE_URL: "postgresql://affine:{{ requiredEnv \"AFFINE_DB_PASSWORD\" }}@{{ requiredEnv \"AFFINE_DB_HOST\" }}/affine"
          NODE_ENV: production
          AFFINE_ENV: production
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

service:
  app:
    controller: affine
    ports:
      http:
        port: 3010

ingress:
  app:
    enabled: false
