# List of external services to be reverse-proxied by Traefik.
# - host: The subdomain (will be prefixed to .{{ requiredEnv "DOMAIN" }})
# - destination: The destination IP address or hostname
# - layer: 4 (TCP - TLS Passthrough) or 7 (HTTP - TLS Termination)
# - port: The destination port

services:
- host: nas
  destination: 192.168.1.63
  layer: 4
  port: 443
- host: mail
  destination: 192.168.1.9
  layer: 4
  port: 443
- host: haos
  destination: 192.168.1.42
  layer: 7
  port: 8123
