apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-external-services
  namespace: traefik
data:
  services.yaml: |
    http:
      routers:
        haos:
          entryPoints:
            - websecure
          rule: Host(`haos.thivillon.org`)
          service: haos
          tls:
            certResolver: letsencrypt
      services:
        haos:
          loadBalancer:
            servers:
              - url: http://192.168.1.42:8123
    tcp:
      routers:
        nas:
          entryPoints:
            - websecure
          rule: HostSNI(`nas.thivillon.org`)
          service: nas
          tls:
            passthrough: true
        mail:
          entryPoints:
            - websecure
          rule: HostSNI(`mail.thivillon.org`)
          service: mail
          tls:
            passthrough: true
      services:
        nas:
          loadBalancer:
            servers:
              - address: 192.168.1.63:443
        mail:
          loadBalancer:
            servers:
              - address: 192.168.1.9:443
