---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBJf1Ae2TsDUmNqlabvR86V2g24onC9ms+IxKV48aaS5Y/o5BwtbiangY/xQ37yU//s8KGns8whlchdYggn01l7cIPC3n/TOWKaWVNaJE1v2hXYNSv/kwMJSl27lVAMeEEBYwl3zyQ837lE3MLFUQcPtEKbk+eOg85Oz4/yb5U+6PupQDQ9YYrIXpCyILV91l+RU/NHAoiq50JPxhbprVmGbv4p7IYUoVUKfJGdQk144Tmh5ZvvmRLUNQmPJRudG1vkdNd7MbjjBGxPmtTeB2qCW07ln/3+9AgxUc5S6FT0rPPaTunC69t89etinipWUwVMzZ7uW/fsDGhovjGYcqJbhA5hw8z3HAm2LmjQQLKeo4rqaQVVzz23jlAuu2xyYhpi4gtsrnsARxALIkBgoqgO4lXUll/rsz4Cj8it7x+xw6hQacnhfEp2EGubrezPG9hVaXkrFs5IvEOTxE/bB96O5zMnxisF01lX8QbRbPyEFIs4m6hqEA5co/EoT9AcVvMOY+DtVFI1G98Utr4ZhpycV7FrluBPCFOMfvHURRcS752BY/juSxvR+etrRJX4HX5bIFcyXUotF6GUiyoVEkhaye6fO9SQo3T/ca7H4TtJoS6wpaT6WWvt660nXLZs7hpRsoA4ao3/oZWiCKGV7gry5QbO5RtiPKT9/aWYDIAkn4LX/u4Iaetd3ztz5ACQn7l4LU1k8Zu2XJJ8AqqCa9oxVzzksqGjIJhDESHIiEnYUnAZWfniRs9iGGkXuFEKOzAYZAClyQ==
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: traefik
